output: docs
author: gematik GmbH
author_url: http://www.gematik.de
exclude: /*/internal*
module: DemoApp
github_url: https://github.com/gematik/ref-OpenHealthCardApp-iOS
theme: jony
xcodebuild_arguments:
  - "-project"
  - 'DemoApp.xcodeproj'
  - "-scheme"
  - 'DemoApp'
