output: docs
author: gematik Gesellschaft für Telematikanwendungen der Gesundheitskarte mbH
author_url: http://www.gematik.de
exclude: /*/internal*
module: DemoApp
github_url: http://www.github.com/gematik/openhealthcardapp-ios.git
theme: jony
xcodebuild_arguments:
  - "-project"
  - 'DemoApp.xcodeproj'
  - "-scheme"
  - 'DemoApp'
